### ISSUE TITLE
Sample code for remove method of LinkedList class is non-functional.

### ISSUE THREAD

**Issue by mejia-dev** [epicodus-curriculum/capstone#17]
The final remove method code sample at https://github.com/epicodus-curriculum/capstone/blob/main/linked_lists.md is as follows:

```javascript
remove(indexToRemove) {
  if (index === 0) {
    this.head = this.head.next;
  } else {
    let currentNode = this.head;
    let currentIndex = 0;
    while ((currentIndex +1 ) <= index) {
      if (currentNode.next === null ) {
        return -1;
      }
      if ((currentIndex + 1) === index) {
        currentNode.next = currentNode.next.next;
        break;
      }
      currentNode = currentNode.next;
      currentIndex++;
    }
  }
}
```

`indexToRemove` is passed in as an argument but is not referenced within the body of the method. Updating the `index` references to be `indexToRemove` resolves the issue and matches with the prior code samples provided in the lesson.

**Comment by erik-t-irgens** [comment]
Great catch, and great fix.
